from syllib import *

END_POINTS = [BARBARA, CELARENT, DARII, FERIO, '1AAI', '1EAO']

def reduces_by_contradiction(syls):
  #~ for syl in syls:
    #~ print(syl.name(), end = ', ')
  #~ print('')
  if syls[-1].name() in END_POINTS:
    return True
  if syls[-1].name() in [s.name() for s in syls[:-1]]:
    return False
  l = len(syls)
  for contra in syls[-1].contradict():
    if not contra.valid():
      continue
    del syls[l:]
    syls.append(contra)
    if reduces_by_contradiction(syls):
      return True
  return False


for figure in range(1, 5):
  for major in [A, E, I, O]:
    for minor in [A, E, I, O]:
      for conclusion in [A, E, I, O]:
        syl = Syllogism.gen_syllogism(figure, major, minor, conclusion)
        if syl.valid():
          chain = [syl]
          if reduces_by_contradiction(chain):
            #~ pass
            print('SUCCESS: ', end = '')
            for syl in chain:
              print(syl.name(), end = ', ')
            print('')
          else:
            print('FAIL: ', end = '')
            for syl in chain:
              print(syl.name(), end = ', ')
            print('')

"""RESULTS:
===All possible chains:
Barbara,
Barbara, Baroco,
Barbara, Baroco, Barbara,
Barbara, Baroco, Bocardo,
Barbara, Baroco, Bocardo, Baroco,
Barbara, Baroco, Bocardo, Barbara,
Barbara, Bocardo,
Barbara, Bocardo, Baroco,
Barbara, Bocardo, Baroco, Barbara,
Barbara, Bocardo, Baroco, Bocardo,
Barbara, Bocardo, Barbara,
1AAI,
1AAI, 2AEO,
1AAI, 2AEO, 1AAI,
1AAI, 2AEO, Felapton,
1AAI, 2AEO, Felapton, 2AEO,
1AAI, 2AEO, Felapton, 1AAI,
1AAI, Felapton,
1AAI, Felapton, 2AEO,
1AAI, Felapton, 2AEO, 1AAI,
1AAI, Felapton, 2AEO, Felapton,
1AAI, Felapton, 1AAI,
Darii,
Darii, Camestres,
Darii, Camestres, Darii,
Darii, Camestres, Ferison,
Darii, Camestres, Ferison, Camestres,
Darii, Camestres, Ferison, Darii,
Darii, Ferison,
Darii, Ferison, Camestres,
Darii, Ferison, Camestres, Darii,
Darii, Ferison, Camestres, Ferison,
Darii, Ferison, Darii,
Celarent,
Celarent, Festino,
Celarent, Festino, Celarent,
Celarent, Festino, Disamis,
Celarent, Festino, Disamis, Festino,
Celarent, Festino, Disamis, Celarent,
Celarent, Disamis,
Celarent, Disamis, Festino,
Celarent, Disamis, Festino, Celarent,
Celarent, Disamis, Festino, Disamis,
Celarent, Disamis, Celarent,
1EAO,
1EAO, 2EAO,
1EAO, 2EAO, 1EAO,
1EAO, 2EAO, Darapti,
1EAO, 2EAO, Darapti, 2EAO,
1EAO, 2EAO, Darapti, 1EAO,
1EAO, Darapti,
1EAO, Darapti, 2EAO,
1EAO, Darapti, 2EAO, 1EAO,
1EAO, Darapti, 2EAO, Darapti,
1EAO, Darapti, 1EAO,
Ferio,
Ferio, Cesare,
Ferio, Cesare, Ferio,
Ferio, Cesare, Datisi,
Ferio, Cesare, Datisi, Cesare,
Ferio, Cesare, Datisi, Ferio,
Ferio, Datisi,
Ferio, Datisi, Cesare,
Ferio, Datisi, Cesare, Ferio,
Ferio, Datisi, Cesare, Datisi,
Ferio, Datisi, Ferio,
Camestres,
Camestres, Darii,
Camestres, Darii, Camestres,
Camestres, Darii, Ferison,
Camestres, Darii, Ferison, Camestres,
Camestres, Darii, Ferison, Darii,
Camestres, Ferison,
Camestres, Ferison, Camestres,
Camestres, Ferison, Darii,
Camestres, Ferison, Darii, Camestres,
Camestres, Ferison, Darii, Ferison,
2AEO,
2AEO, 1AAI,
2AEO, 1AAI, 2AEO,
2AEO, 1AAI, Felapton,
2AEO, 1AAI, Felapton, 2AEO,
2AEO, 1AAI, Felapton, 1AAI,
2AEO, Felapton,
2AEO, Felapton, 2AEO,
2AEO, Felapton, 1AAI,
2AEO, Felapton, 1AAI, 2AEO,
2AEO, Felapton, 1AAI, Felapton,
Baroco,
Baroco, Barbara,
Baroco, Barbara, Baroco,
Baroco, Barbara, Bocardo,
Baroco, Barbara, Bocardo, Baroco,
Baroco, Barbara, Bocardo, Barbara,
Baroco, Bocardo,
Baroco, Bocardo, Baroco,
Baroco, Bocardo, Barbara,
Baroco, Bocardo, Barbara, Baroco,
Baroco, Bocardo, Barbara, Bocardo,
Cesare,
Cesare, Ferio,
Cesare, Ferio, Cesare,
Cesare, Ferio, Datisi,
Cesare, Ferio, Datisi, Cesare,
Cesare, Ferio, Datisi, Ferio,
Cesare, Datisi,
Cesare, Datisi, Cesare,
Cesare, Datisi, Ferio,
Cesare, Datisi, Ferio, Cesare,
Cesare, Datisi, Ferio, Datisi,
2EAO,
2EAO, 1EAO,
2EAO, 1EAO, 2EAO,
2EAO, 1EAO, Darapti,
2EAO, 1EAO, Darapti, 2EAO,
2EAO, 1EAO, Darapti, 1EAO,
2EAO, Darapti,
2EAO, Darapti, 2EAO,
2EAO, Darapti, 1EAO,
2EAO, Darapti, 1EAO, 2EAO,
2EAO, Darapti, 1EAO, Darapti,
Festino,
Festino, Celarent,
Festino, Celarent, Festino,
Festino, Celarent, Disamis,
Festino, Celarent, Disamis, Festino,
Festino, Celarent, Disamis, Celarent,
Festino, Disamis,
Festino, Disamis, Festino,
Festino, Disamis, Celarent,
Festino, Disamis, Celarent, Festino,
Festino, Disamis, Celarent, Disamis,
Darapti,
Darapti, 2EAO,
Darapti, 2EAO, 1EAO,
Darapti, 2EAO, 1EAO, 2EAO,
Darapti, 2EAO, 1EAO, Darapti,
Darapti, 2EAO, Darapti,
Darapti, 1EAO,
Darapti, 1EAO, 2EAO,
Darapti, 1EAO, 2EAO, 1EAO,
Darapti, 1EAO, 2EAO, Darapti,
Darapti, 1EAO, Darapti,
Datisi,
Datisi, Cesare,
Datisi, Cesare, Ferio,
Datisi, Cesare, Ferio, Cesare,
Datisi, Cesare, Ferio, Datisi,
Datisi, Cesare, Datisi,
Datisi, Ferio,
Datisi, Ferio, Cesare,
Datisi, Ferio, Cesare, Ferio,
Datisi, Ferio, Cesare, Datisi,
Datisi, Ferio, Datisi,
Felapton,
Felapton, 2AEO,
Felapton, 2AEO, 1AAI,
Felapton, 2AEO, 1AAI, 2AEO,
Felapton, 2AEO, 1AAI, Felapton,
Felapton, 2AEO, Felapton,
Felapton, 1AAI,
Felapton, 1AAI, 2AEO,
Felapton, 1AAI, 2AEO, 1AAI,
Felapton, 1AAI, 2AEO, Felapton,
Felapton, 1AAI, Felapton,
Ferison,
Ferison, Camestres,
Ferison, Camestres, Darii,
Ferison, Camestres, Darii, Camestres,
Ferison, Camestres, Darii, Ferison,
Ferison, Camestres, Ferison,
Ferison, Darii,
Ferison, Darii, Camestres,
Ferison, Darii, Camestres, Darii,
Ferison, Darii, Camestres, Ferison,
Ferison, Darii, Ferison,
Disamis,
Disamis, Festino,
Disamis, Festino, Celarent,
Disamis, Festino, Celarent, Festino,
Disamis, Festino, Celarent, Disamis,
Disamis, Festino, Disamis,
Disamis, Celarent,
Disamis, Celarent, Festino,
Disamis, Celarent, Festino, Celarent,
Disamis, Celarent, Festino, Disamis,
Disamis, Celarent, Disamis,
Bocardo,
Bocardo, Baroco,
Bocardo, Baroco, Barbara,
Bocardo, Baroco, Barbara, Baroco,
Bocardo, Baroco, Barbara, Bocardo,
Bocardo, Baroco, Bocardo,
Bocardo, Barbara,
Bocardo, Barbara, Baroco,
Bocardo, Barbara, Baroco, Barbara,
Bocardo, Barbara, Baroco, Bocardo,
Bocardo, Barbara, Bocardo,
Bramantip,
Bramantip, Fesapo,
Bramantip, Fesapo, 4AEO,
Bramantip, Fesapo, 4AEO, Bramantip,
Bramantip, Fesapo, 4AEO, Fesapo,
Bramantip, Fesapo, Bramantip,
Bramantip, 4AEO,
Bramantip, 4AEO, Bramantip,
Bramantip, 4AEO, Fesapo,
Bramantip, 4AEO, Fesapo, 4AEO,
Bramantip, 4AEO, Fesapo, Bramantip,
4AAO,
4AAO, 4AAO,
4AAO, 4AAO,
Calemes,
Calemes, Dimatis,
Calemes, Dimatis, Fresison,
Calemes, Dimatis, Fresison, Calemes,
Calemes, Dimatis, Fresison, Dimatis,
Calemes, Dimatis, Calemes,
Calemes, Fresison,
Calemes, Fresison, Calemes,
Calemes, Fresison, Dimatis,
Calemes, Fresison, Dimatis, Fresison,
Calemes, Fresison, Dimatis, Calemes,
4AEO,
4AEO, Bramantip,
4AEO, Bramantip, Fesapo,
4AEO, Bramantip, Fesapo, 4AEO,
4AEO, Bramantip, Fesapo, Bramantip,
4AEO, Bramantip, 4AEO,
4AEO, Fesapo,
4AEO, Fesapo, 4AEO,
4AEO, Fesapo, Bramantip,
4AEO, Fesapo, Bramantip, Fesapo,
4AEO, Fesapo, Bramantip, 4AEO,
Fesapo,
Fesapo, 4AEO,
Fesapo, 4AEO, Bramantip,
Fesapo, 4AEO, Bramantip, Fesapo,
Fesapo, 4AEO, Bramantip, 4AEO,
Fesapo, 4AEO, Fesapo,
Fesapo, Bramantip,
Fesapo, Bramantip, Fesapo,
Fesapo, Bramantip, 4AEO,
Fesapo, Bramantip, 4AEO, Bramantip,
Fesapo, Bramantip, 4AEO, Fesapo,
Fresison,
Fresison, Calemes,
Fresison, Calemes, Dimatis,
Fresison, Calemes, Dimatis, Fresison,
Fresison, Calemes, Dimatis, Calemes,
Fresison, Calemes, Fresison,
Fresison, Dimatis,
Fresison, Dimatis, Fresison,
Fresison, Dimatis, Calemes,
Fresison, Dimatis, Calemes, Dimatis,
Fresison, Dimatis, Calemes, Fresison,
Dimatis,
Dimatis, Fresison,
Dimatis, Fresison, Calemes,
Dimatis, Fresison, Calemes, Dimatis,
Dimatis, Fresison, Calemes, Fresison,
Dimatis, Fresison, Dimatis,
Dimatis, Calemes,
Dimatis, Calemes, Dimatis,
Dimatis, Calemes, Fresison,
Dimatis, Calemes, Fresison, Calemes,
Dimatis, Calemes, Fresison, Dimatis,

===Success/fail to Barbara and Celarent
SUCCESS: Barbara,
FAIL: 1AAI, Felapton, 1AAI,
FAIL: Darii, Ferison, Darii,
SUCCESS: Celarent,
FAIL: 1EAO, Darapti, 1EAO,
FAIL: Ferio, Datisi, Ferio,
FAIL: Camestres, Ferison, Darii, Ferison,
FAIL: 2AEO, Felapton, 1AAI, Felapton,
SUCCESS: Baroco, Barbara,
FAIL: Cesare, Datisi, Ferio, Datisi,
FAIL: 2EAO, Darapti, 1EAO, Darapti,
SUCCESS: Festino, Celarent,
FAIL: Darapti, 1EAO, Darapti,
FAIL: Datisi, Ferio, Datisi,
FAIL: Felapton, 1AAI, Felapton,
FAIL: Ferison, Darii, Ferison,
SUCCESS: Disamis, Festino, Celarent,
SUCCESS: Bocardo, Baroco, Barbara,
FAIL: Bramantip, 4AEO, Fesapo, Bramantip,
FAIL: 4AAO, 4AAO,
FAIL: Calemes, Fresison, Dimatis, Calemes,
FAIL: 4AEO, Fesapo, Bramantip, 4AEO,
FAIL: Fesapo, Bramantip, 4AEO, Fesapo,
FAIL: Fresison, Dimatis, Calemes, Fresison,
FAIL: Dimatis, Calemes, Fresison, Dimatis,

===Success/fail to Barbara, Celarent, Darii, Ferio
SUCCESS: Barbara,
FAIL: 1AAI, Felapton, 1AAI,
SUCCESS: Darii,
SUCCESS: Celarent,
FAIL: 1EAO, Darapti, 1EAO,
SUCCESS: Ferio,
SUCCESS: Camestres, Darii,
FAIL: 2AEO, Felapton, 1AAI, Felapton,
SUCCESS: Baroco, Barbara,
SUCCESS: Cesare, Ferio,
FAIL: 2EAO, Darapti, 1EAO, Darapti,
SUCCESS: Festino, Celarent,
FAIL: Darapti, 1EAO, Darapti,
SUCCESS: Datisi, Cesare, Ferio,
FAIL: Felapton, 1AAI, Felapton,
SUCCESS: Ferison, Camestres, Darii,
SUCCESS: Disamis, Festino, Celarent,
SUCCESS: Bocardo, Baroco, Barbara,
FAIL: Bramantip, 4AEO, Fesapo, Bramantip,
FAIL: 4AAO, 4AAO,
FAIL: Calemes, Fresison, Dimatis, Calemes,
FAIL: 4AEO, Fesapo, Bramantip, 4AEO,
FAIL: Fesapo, Bramantip, 4AEO, Fesapo,
FAIL: Fresison, Dimatis, Calemes, Fresison,
FAIL: Dimatis, Calemes, Fresison, Dimatis,

===Success/fail to any first figure (Barbara, Celarent, Darii, Ferio, 1AAI, 1EAO)
SUCCESS: Barbara,
SUCCESS: 1AAI,
SUCCESS: Darii,
SUCCESS: Celarent,
SUCCESS: 1EAO,
SUCCESS: Ferio,
SUCCESS: Camestres, Darii,
SUCCESS: 2AEO, 1AAI,
SUCCESS: Baroco, Barbara,
SUCCESS: Cesare, Ferio,
SUCCESS: 2EAO, 1EAO,
SUCCESS: Festino, Celarent,
SUCCESS: Darapti, 2EAO, 1EAO,
SUCCESS: Datisi, Cesare, Ferio,
SUCCESS: Felapton, 2AEO, 1AAI,
SUCCESS: Ferison, Camestres, Darii,
SUCCESS: Disamis, Festino, Celarent,
SUCCESS: Bocardo, Baroco, Barbara,
FAIL: Bramantip, 4AEO, Fesapo, Bramantip,
FAIL: 4AAO, 4AAO,
FAIL: Calemes, Fresison, Dimatis, Calemes,
FAIL: 4AEO, Fesapo, Bramantip, 4AEO,
FAIL: Fesapo, Bramantip, 4AEO, Fesapo,
FAIL: Fresison, Dimatis, Calemes, Fresison,
FAIL: Dimatis, Calemes, Fresison, Dimatis,
"""
